/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.pocketcampus.plugin.news.shared;

import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;

public class NewsFeedsRequest implements org.apache.thrift.TBase<NewsFeedsRequest, NewsFeedsRequest._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("NewsFeedsRequest");

  private static final org.apache.thrift.protocol.TField LANGUAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("language", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField GENERAL_FEED_INCLUDED_FIELD_DESC = new org.apache.thrift.protocol.TField("generalFeedIncluded", org.apache.thrift.protocol.TType.BOOL, (short)2);

  private String language; // required
  private boolean generalFeedIncluded; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LANGUAGE((short)1, "language"),
    GENERAL_FEED_INCLUDED((short)2, "generalFeedIncluded");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LANGUAGE
          return LANGUAGE;
        case 2: // GENERAL_FEED_INCLUDED
          return GENERAL_FEED_INCLUDED;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __GENERALFEEDINCLUDED_ISSET_ID = 0;
  private BitSet __isset_bit_vector = new BitSet(1);

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LANGUAGE, new org.apache.thrift.meta_data.FieldMetaData("language", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.GENERAL_FEED_INCLUDED, new org.apache.thrift.meta_data.FieldMetaData("generalFeedIncluded", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(NewsFeedsRequest.class, metaDataMap);
  }

  public NewsFeedsRequest() {
  }

  public NewsFeedsRequest(
    String language,
    boolean generalFeedIncluded)
  {
    this();
    this.language = language;
    this.generalFeedIncluded = generalFeedIncluded;
    setGeneralFeedIncludedIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public NewsFeedsRequest(NewsFeedsRequest other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    if (other.isSetLanguage()) {
      this.language = other.language;
    }
    this.generalFeedIncluded = other.generalFeedIncluded;
  }

  public NewsFeedsRequest deepCopy() {
    return new NewsFeedsRequest(this);
  }

  @Override
  public void clear() {
    this.language = null;
    setGeneralFeedIncludedIsSet(false);
    this.generalFeedIncluded = false;
  }

  public String getLanguage() {
    return this.language;
  }

  public NewsFeedsRequest setLanguage(String language) {
    this.language = language;
    return this;
  }

  public void unsetLanguage() {
    this.language = null;
  }

  /** Returns true if field language is set (has been assigned a value) and false otherwise */
  public boolean isSetLanguage() {
    return this.language != null;
  }

  public void setLanguageIsSet(boolean value) {
    if (!value) {
      this.language = null;
    }
  }

  public boolean isGeneralFeedIncluded() {
    return this.generalFeedIncluded;
  }

  public NewsFeedsRequest setGeneralFeedIncluded(boolean generalFeedIncluded) {
    this.generalFeedIncluded = generalFeedIncluded;
    setGeneralFeedIncludedIsSet(true);
    return this;
  }

  public void unsetGeneralFeedIncluded() {
    __isset_bit_vector.clear(__GENERALFEEDINCLUDED_ISSET_ID);
  }

  /** Returns true if field generalFeedIncluded is set (has been assigned a value) and false otherwise */
  public boolean isSetGeneralFeedIncluded() {
    return __isset_bit_vector.get(__GENERALFEEDINCLUDED_ISSET_ID);
  }

  public void setGeneralFeedIncludedIsSet(boolean value) {
    __isset_bit_vector.set(__GENERALFEEDINCLUDED_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case LANGUAGE:
      if (value == null) {
        unsetLanguage();
      } else {
        setLanguage((String)value);
      }
      break;

    case GENERAL_FEED_INCLUDED:
      if (value == null) {
        unsetGeneralFeedIncluded();
      } else {
        setGeneralFeedIncluded((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case LANGUAGE:
      return getLanguage();

    case GENERAL_FEED_INCLUDED:
      return Boolean.valueOf(isGeneralFeedIncluded());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case LANGUAGE:
      return isSetLanguage();
    case GENERAL_FEED_INCLUDED:
      return isSetGeneralFeedIncluded();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof NewsFeedsRequest)
      return this.equals((NewsFeedsRequest)that);
    return false;
  }

  public boolean equals(NewsFeedsRequest that) {
    if (that == null)
      return false;

    boolean this_present_language = true && this.isSetLanguage();
    boolean that_present_language = true && that.isSetLanguage();
    if (this_present_language || that_present_language) {
      if (!(this_present_language && that_present_language))
        return false;
      if (!this.language.equals(that.language))
        return false;
    }

    boolean this_present_generalFeedIncluded = true;
    boolean that_present_generalFeedIncluded = true;
    if (this_present_generalFeedIncluded || that_present_generalFeedIncluded) {
      if (!(this_present_generalFeedIncluded && that_present_generalFeedIncluded))
        return false;
      if (this.generalFeedIncluded != that.generalFeedIncluded)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_language = true && (isSetLanguage());
    builder.append(present_language);
    if (present_language)
      builder.append(language);

    boolean present_generalFeedIncluded = true;
    builder.append(present_generalFeedIncluded);
    if (present_generalFeedIncluded)
      builder.append(generalFeedIncluded);

    return builder.toHashCode();
  }

  public int compareTo(NewsFeedsRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    NewsFeedsRequest typedOther = (NewsFeedsRequest)other;

    lastComparison = Boolean.valueOf(isSetLanguage()).compareTo(typedOther.isSetLanguage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLanguage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.language, typedOther.language);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetGeneralFeedIncluded()).compareTo(typedOther.isSetGeneralFeedIncluded());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGeneralFeedIncluded()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.generalFeedIncluded, typedOther.generalFeedIncluded);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    org.apache.thrift.protocol.TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == org.apache.thrift.protocol.TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // LANGUAGE
          if (field.type == org.apache.thrift.protocol.TType.STRING) {
            this.language = iprot.readString();
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // GENERAL_FEED_INCLUDED
          if (field.type == org.apache.thrift.protocol.TType.BOOL) {
            this.generalFeedIncluded = iprot.readBool();
            setGeneralFeedIncludedIsSet(true);
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    if (!isSetGeneralFeedIncluded()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'generalFeedIncluded' was not found in serialized data! Struct: " + toString());
    }
    validate();
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.language != null) {
      oprot.writeFieldBegin(LANGUAGE_FIELD_DESC);
      oprot.writeString(this.language);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(GENERAL_FEED_INCLUDED_FIELD_DESC);
    oprot.writeBool(this.generalFeedIncluded);
    oprot.writeFieldEnd();
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("NewsFeedsRequest(");
    boolean first = true;

    sb.append("language:");
    if (this.language == null) {
      sb.append("null");
    } else {
      sb.append(this.language);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("generalFeedIncluded:");
    sb.append(this.generalFeedIncluded);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (language == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'language' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'generalFeedIncluded' because it's a primitive and you chose the non-beans generator.
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

}

