
REPLACE INTO `eventitems` 
SET 
	`eventId` 		= 126000000, 
	`startDate` 	= '2015-02-03 14:00:00', 
	`endDate` 		= '2015-02-03 16:30:00', 
	`fullDay` 		= NULL, 
	`eventPicture` 	= NULL, 
	`eventThumbnail` = 'http://pocketcampus.epfl.ch/events/forumit2015_1/images/logo.jpg', 
	`eventTitle` 	= 'Forum des Systèmes d\'Information', 
	`eventTitle_fr`	= NULL, 
	`eventPlace` 	= 'STCC - Garden 5ABC', 
	`eventSpeaker` 	= NULL, 
	`eventDetails` 	= NULL, 
	`eventDetails_fr` = NULL, 
	`parentPool` 	= -1, 
	`eventUri` 		= NULL, 
	`vcalUid` 		= NULL, 
	`eventCateg` 	= -1, 
	`broadcastInFeeds` = 'ic', 
	`locationHref` 	= NULL, 
	`detailsLink` 	= NULL, 
	`secondLine` 	= 'STCC - Garden 5ABC', 
	`timeSnippet` 	= NULL, 
	`hideEventInfo` = 1, 
	`hideTitle` 	= NULL, 
	`hideThumbnail` = NULL, 
	`isProtected` 	= 1;


REPLACE INTO `eventitems` 
SET 
	`eventId` 		= 126010001, 
	`startDate` 	= '2015-02-03 14:00:00', 
	`endDate` 		= '2015-02-03 14:10:00', 
	`fullDay` 		= NULL, 
	`eventPicture` 	= NULL, 
	`eventThumbnail` = 'http://people.epfl.ch/cgi-bin/people/getPhoto?id=134136&show=', 
	`eventTitle` 	= 'Le Mot du Vice-Président', 
	`eventTitle_fr`	= NULL, 
	`eventPlace` 	= NULL, 
	`eventSpeaker` 	= NULL, 
	`eventDetails` 	= '<a href="pocketcampus://directory.plugin.pocketcampus.org/search?q=karl.aberer">Karl Aberer</a>', 
	`eventDetails_fr` = NULL, 
	`parentPool` 	= 26000010, 
	`eventUri` 		= NULL, 
	`vcalUid` 		= NULL, 
	`eventCateg` 	= 111, 
	`broadcastInFeeds` = NULL, 
	`locationHref` 	= NULL, 
	`detailsLink` 	= NULL, 
	`secondLine` 	= 'Karl Aberer', 
	`timeSnippet` 	= NULL, 
	`hideEventInfo` = NULL, 
	`hideTitle` 	= NULL, 
	`hideThumbnail` = NULL, 
	`isProtected` 	= NULL;


REPLACE INTO `eventitems` 
SET 
	`eventId` 		= 126010002, 
	`startDate` 	= '2015-02-03 14:15:00', 
	`endDate` 		= '2015-02-03 14:30:00', 
	`fullDay` 		= NULL, 
	`eventPicture` 	= NULL, 
	`eventThumbnail` = 'http://people.epfl.ch/cgi-bin/people/getPhoto?id=157873&show=', 
	`eventTitle` 	= 'Les MOOCs, côté pile et face', 
	`eventTitle_fr`	= NULL, 
	`eventPlace` 	= NULL, 
	`eventSpeaker` 	= NULL, 
	`eventDetails` 	= '<a href="pocketcampus://directory.plugin.pocketcampus.org/search?q=patrick.jermann">Patrick Jermann</a>', 
	`eventDetails_fr` = NULL, 
	`parentPool` 	= 26000010, 
	`eventUri` 		= NULL, 
	`vcalUid` 		= NULL, 
	`eventCateg` 	= 111, 
	`broadcastInFeeds` = NULL, 
	`locationHref` 	= NULL, 
	`detailsLink` 	= NULL, 
	`secondLine` 	= 'Patrick Jermann', 
	`timeSnippet` 	= NULL, 
	`hideEventInfo` = NULL, 
	`hideTitle` 	= NULL, 
	`hideThumbnail` = NULL, 
	`isProtected` 	= NULL;


REPLACE INTO `eventitems` 
SET 
	`eventId` 		= 126010003, 
	`startDate` 	= '2015-02-03 14:35:00', 
	`endDate` 		= '2015-02-03 14:50:00', 
	`fullDay` 		= NULL, 
	`eventPicture` 	= NULL, 
	`eventThumbnail` = 'http://pocketcampus.epfl.ch/events/forumit2015_1/images/logo.jpg', 
	`eventTitle` 	= 'La gestion du stockage à l\'EPFL', 
	`eventTitle_fr`	= NULL, 
	`eventPlace` 	= NULL, 
	`eventSpeaker` 	= NULL, 
	`eventDetails` 	= '<a href="pocketcampus://directory.plugin.pocketcampus.org/search?q=sofiane.sarni">Sofiane Sarni</a>', 
	`eventDetails_fr` = NULL, 
	`parentPool` 	= 26000010, 
	`eventUri` 		= NULL, 
	`vcalUid` 		= NULL, 
	`eventCateg` 	= 111, 
	`broadcastInFeeds` = NULL, 
	`locationHref` 	= NULL, 
	`detailsLink` 	= NULL, 
	`secondLine` 	= 'Sofiane Sarni', 
	`timeSnippet` 	= NULL, 
	`hideEventInfo` = NULL, 
	`hideTitle` 	= NULL, 
	`hideThumbnail` = NULL, 
	`isProtected` 	= NULL;


REPLACE INTO `eventitems` 
SET 
	`eventId` 		= 126010004, 
	`startDate` 	= '2015-02-03 14:50:00', 
	`endDate` 		= '2015-02-03 15:10:00', 
	`fullDay` 		= NULL, 
	`eventPicture` 	= NULL, 
	`eventThumbnail` = 'http://www.downeastcoffee.ca/sites/default/files/media/slides/coffee.png', 
	`eventTitle` 	= 'Pause café', 
	`eventTitle_fr`	= NULL, 
	`eventPlace` 	= NULL, 
	`eventSpeaker` 	= NULL, 
	`eventDetails` 	= '', 
	`eventDetails_fr` = NULL, 
	`parentPool` 	= 26000010, 
	`eventUri` 		= NULL, 
	`vcalUid` 		= NULL, 
	`eventCateg` 	= 111, 
	`broadcastInFeeds` = NULL, 
	`locationHref` 	= NULL, 
	`detailsLink` 	= NULL, 
	`secondLine` 	= NULL, 
	`timeSnippet` 	= NULL, 
	`hideEventInfo` = NULL, 
	`hideTitle` 	= NULL, 
	`hideThumbnail` = NULL, 
	`isProtected` 	= NULL;


REPLACE INTO `eventitems` 
SET 
	`eventId` 		= 126010005, 
	`startDate` 	= '2015-02-03 15:15:00', 
	`endDate` 		= '2015-02-03 15:30:00', 
	`fullDay` 		= NULL, 
	`eventPicture` 	= NULL, 
	`eventThumbnail` = 'http://people.epfl.ch/cgi-bin/people/getPhoto?id=164486&show=', 
	`eventTitle` 	= 'Le web sous tous les formats', 
	`eventTitle_fr`	= NULL, 
	`eventPlace` 	= NULL, 
	`eventSpeaker` 	= NULL, 
	`eventDetails` 	= '<a href="pocketcampus://directory.plugin.pocketcampus.org/search?q=pierre.mellier">Pierre Mellier</a>', 
	`eventDetails_fr` = NULL, 
	`parentPool` 	= 26000010, 
	`eventUri` 		= NULL, 
	`vcalUid` 		= NULL, 
	`eventCateg` 	= 111, 
	`broadcastInFeeds` = NULL, 
	`locationHref` 	= NULL, 
	`detailsLink` 	= NULL, 
	`secondLine` 	= 'Pierre Mellier', 
	`timeSnippet` 	= NULL, 
	`hideEventInfo` = NULL, 
	`hideTitle` 	= NULL, 
	`hideThumbnail` = NULL, 
	`isProtected` 	= NULL;


REPLACE INTO `eventitems` 
SET 
	`eventId` 		= 126010006, 
	`startDate` 	= '2015-02-03 15:35:00', 
	`endDate` 		= '2015-02-03 16:05:00', 
	`fullDay` 		= NULL, 
	`eventPicture` 	= NULL, 
	`eventThumbnail` = 'http://pocketcampus.epfl.ch/events/forumit2015_1/images/logo.jpg', 
	`eventTitle` 	= 'Évolution des systèmes d\'information à l\'EPFL', 
	`eventTitle_fr`	= NULL, 
	`eventPlace` 	= NULL, 
	`eventSpeaker` 	= NULL, 
	`eventDetails` 	= NULL, 
	`eventDetails_fr` = NULL, 
	`parentPool` 	= 26000010, 
	`eventUri` 		= NULL, 
	`vcalUid` 		= NULL, 
	`eventCateg` 	= 111, 
	`broadcastInFeeds` = NULL, 
	`locationHref` 	= NULL, 
	`detailsLink` 	= NULL, 
	`secondLine` 	= 'Karl Aberer et un panel de membres de la VPSI', 
	`timeSnippet` 	= NULL, 
	`hideEventInfo` = NULL, 
	`hideTitle` 	= NULL, 
	`hideThumbnail` = NULL, 
	`isProtected` 	= NULL;


REPLACE INTO `eventitems` 
SET 
	`eventId` 		= 126010007, 
	`startDate` 	= '2015-02-03 16:05:00', 
	`endDate` 		= '2015-02-03 17:00:00', 
	`fullDay` 		= NULL, 
	`eventPicture` 	= NULL, 
	`eventThumbnail` = 'http://www.traiteur-casino.com/19-627-thickbox/feuilletes-aperitif.jpg', 
	`eventTitle` 	= 'Apéritif', 
	`eventTitle_fr`	= NULL, 
	`eventPlace` 	= NULL, 
	`eventSpeaker` 	= NULL, 
	`eventDetails` 	= NULL, 
	`eventDetails_fr` = NULL, 
	`parentPool` 	= 26000010, 
	`eventUri` 		= NULL, 
	`vcalUid` 		= NULL, 
	`eventCateg` 	= 111, 
	`broadcastInFeeds` = NULL, 
	`locationHref` 	= NULL, 
	`detailsLink` 	= NULL, 
	`secondLine` 	= NULL, 
	`timeSnippet` 	= NULL, 
	`hideEventInfo` = NULL, 
	`hideTitle` 	= NULL, 
	`hideThumbnail` = NULL, 
	`isProtected` 	= NULL;


REPLACE INTO `eventitems` 
SET 
	`eventId` 		= 126020001, 
	`startDate` 	= '2015-02-03 14:30:00', 
	`endDate` 		= '2015-02-03 17:00:00', 
	`fullDay` 		= NULL, 
	`eventPicture` 	= NULL, 
	`eventThumbnail` = 'http://fr.hdyo.org/assets/ask-question-2-fb180173e13f21ad6ae73ba29b08cd02.jpg', 
	`eventTitle` 	= 'Poser une question', 
	`eventTitle_fr`	= NULL, 
	`eventPlace` 	= NULL, 
	`eventSpeaker` 	= NULL, 
	`eventDetails` 	= 'Vous pouvez poser une question que les organisateurs de l\'événements verront en direct.<br><br><a href="http://pocketcampus.epfl.ch/backend/comment/question.php"><b>Rédiger une question</b></a>', 
	`eventDetails_fr` = NULL, 
	`parentPool` 	= 26000020, 
	`eventUri` 		= NULL, 
	`vcalUid` 		= NULL, 
	`eventCateg` 	= 111, 
	`broadcastInFeeds` = NULL, 
	`locationHref` 	= NULL, 
	`detailsLink` 	= NULL, 
	`secondLine` 	= NULL, 
	`timeSnippet` 	= NULL, 
	`hideEventInfo` = NULL, 
	`hideTitle` 	= NULL, 
	`hideThumbnail` = NULL, 
	`isProtected` 	= NULL; 


REPLACE INTO `eventpools` 
SET
	`poolId` 		= 26000010, 
	`poolPicture` 	= 'http://pocketcampus.epfl.ch/images/schedule.png', 
	`poolTitle` 	= 'Programme', 
	`poolPlace` 	= NULL, 
	`poolDetails` 	= NULL, 
	`disableStar` 	= 1, 
	`disableFilterByCateg` = 1, 
	`disableFilterByTags` = 1, 
	`enableScan` 	= NULL, 
	`refreshOnBack` = NULL, 
	`sendStarred` 	= NULL, 
	`noResultText` 	= 'Coming soon.', 
	`overrideLink` 	= NULL, 
	`parentEvent` 	= 126000000;


REPLACE INTO `eventpools` 
SET
	`poolId` 		= 26000020, 
	`poolPicture` 	= 'http://pocketcampus.epfl.ch/images/info.png', 
	`poolTitle` 	= 'Poser une question', 
	`poolPlace` 	= NULL, 
	`poolDetails` 	= NULL, 
	`disableStar` 	= 1, 
	`disableFilterByCateg` = 1, 
	`disableFilterByTags` = 1, 
	`enableScan` 	= NULL, 
	`refreshOnBack` = NULL, 
	`sendStarred` 	= NULL, 
	`noResultText` 	= 'Coming soon.', 
	`overrideLink` 	= 'pocketcampus://events.plugin.pocketcampus.org/showEventItem?eventItemId=126020001', 
	`parentEvent` 	= 126000000;

