platform :ios, '7.0'
link_with ['PocketCampus', 'CamiproWidget', 'CloudPrintAction']
pod 'AFNetworking', '~> 2.0'
pod 'thrift', '~> 0.9.1'
pod 'GoogleAnalytics-iOS-SDK',  '~> 3.0'
pod 'CDZQRScanningViewController'
pod 'SSKeychain', '~> 1.2'
pod 'TUSafariActivity'
pod 'NSTimer-Blocks'
pod 'MBProgressHUD'
pod 'JTTargetActionBlock'
pod 'TTTAttributedLabel'
pod 'TapkuLibrary', :git => 'git@github.com:loicgardiol/tapkulibrary.git'
pod 'LGALibrary', :head
