/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.pocketcampus.plugin.satellite.shared;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum SatelliteBeerContainer implements org.apache.thrift.TEnum {
  DRAFT(1),
  BOTTLE(2),
  LARGE_BOTTLE(3);

  private final int value;

  private SatelliteBeerContainer(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SatelliteBeerContainer findByValue(int value) { 
    switch (value) {
      case 1:
        return DRAFT;
      case 2:
        return BOTTLE;
      case 3:
        return LARGE_BOTTLE;
      default:
        return null;
    }
  }
}
