/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.pocketcampus.plugin.transport.shared;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Status implements org.apache.thrift.TEnum {
  sOK(0),
  AMBIGUOUS(1),
  TOO_CLOSE(2),
  UNRESOLVABLE_ADDRESS(3),
  NO_CONNECTIONS(4),
  INVALID_DATE(5),
  SERVICE_DOWN(6);

  private final int value;

  private Status(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Status findByValue(int value) { 
    switch (value) {
      case 0:
        return sOK;
      case 1:
        return AMBIGUOUS;
      case 2:
        return TOO_CLOSE;
      case 3:
        return UNRESOLVABLE_ADDRESS;
      case 4:
        return NO_CONNECTIONS;
      case 5:
        return INVALID_DATE;
      case 6:
        return SERVICE_DOWN;
      default:
        return null;
    }
  }
}
